import { spawn, type ChildProcess } from "node:child_process";
import { createInterface } from "node:readline";
import type { Readable, Writable } from "node:stream";
import type { Config } from "../config.js";

/** Written into each session's rollout (`thread_source`), so CCodex's streaming can find the journal of a call. */
export const MCP_THREAD_SOURCE = "ccodex-mcp";

const RESULT_SCHEMA = { type: "object", properties: { threadId: { type: "string" }, content: { type: "string" } }, required: ["threadId", "content"] };

/** The tools of codex ≤ 0.153's `codex mcp-server`, unchanged, so existing agents and skills keep working. */
const TOOLS = [
  {
    name: "codex",
    title: "Codex",
    description: "Run a Codex session. Accepts configuration parameters matching the Codex Config struct.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      required: ["prompt"],
      properties: {
        prompt: { type: "string", description: "The *initial user prompt* to start the Codex conversation." },
        model: { type: "string", description: "Optional override for the model name (e.g. 'gpt-5.2', 'gpt-5.2-codex')." },
        cwd: { type: "string", description: "Working directory for the session. If relative, it is resolved against the server process's current working directory." },
        sandbox: { type: "string", enum: ["read-only", "workspace-write", "danger-full-access"], description: "Sandbox mode: `read-only`, `workspace-write`, or `danger-full-access`." },
        "approval-policy": { type: "string", enum: ["on-request", "never"], description: "Approval policy for shell commands generated by the model: `on-request`, `never`." },
        config: { type: "object", additionalProperties: true, description: "Individual config settings that will override what is in CODEX_HOME/config.toml." },
        "base-instructions": { type: "string", description: "The set of instructions to use instead of the default ones." },
        "developer-instructions": { type: "string", description: "Developer instructions that should be injected as a developer role message." },
        "compact-prompt": { type: "string", description: "Prompt used when compacting the conversation." },
      },
    },
    outputSchema: RESULT_SCHEMA,
  },
  {
    name: "codex-reply",
    title: "Codex Reply",
    description: "Continue a Codex conversation by providing the thread id and prompt.",
    inputSchema: {
      type: "object",
      required: ["prompt"],
      properties: {
        prompt: { type: "string", description: "The *next user prompt* to continue the Codex conversation." },
        threadId: { type: "string", description: "The thread id for this Codex session." },
        conversationId: { type: "string", description: "DEPRECATED: use threadId instead." },
      },
    },
    outputSchema: RESULT_SCHEMA,
  },
];

type Args = Record<string, any>;

/** `codex exec` arguments for a tool call. */
function execArgs(tool: string, args: Args): string[] {
  const common = ["--json", "--skip-git-repo-check", "--thread-source", MCP_THREAD_SOURCE];
  if (tool === "codex-reply") return ["exec", "resume", ...common, String(args.threadId ?? args.conversationId), "--", String(args.prompt)];
  const overrides: Record<string, unknown> = {
    ...args.config,
    ...(args["approval-policy"] ? { approval_policy: args["approval-policy"] } : {}),
    ...(args["base-instructions"] ? { instructions: args["base-instructions"] } : {}),
    ...(args["developer-instructions"] ? { developer_instructions: args["developer-instructions"] } : {}),
    ...(args["compact-prompt"] ? { compact_prompt: args["compact-prompt"] } : {}),
  };
  return [
    "exec", ...common,
    ...(args.cwd ? ["-C", String(args.cwd)] : []),
    ...(args.model ? ["-m", String(args.model)] : []),
    ...(args.sandbox ? ["-s", String(args.sandbox)] : []),
    ...Object.entries(overrides).flatMap(([key, value]) => ["-c", `${key}=${JSON.stringify(value)}`]),
    "--", String(args.prompt),
  ];
}

/** Runs one call; resolves with the MCP tool result (the session's last agent message). */
function runCall(config: Config, tool: string, args: Args, children: Map<unknown, ChildProcess>, id: unknown): Promise<unknown> {
  return new Promise((resolve) => {
    const child = spawn(config.codex, execArgs(tool, args), { stdio: ["ignore", "pipe", "pipe"], env: { ...process.env, CCODEX_SHIM_ACTIVE: undefined } });
    children.set(id, child);
    let threadId: string = args.threadId ?? args.conversationId ?? "";
    let content = "";
    let error = "";
    let stderr = "";
    createInterface({ input: child.stdout! }).on("line", (line) => {
      try {
        const event = JSON.parse(line) as Args;
        if (event.type === "thread.started") threadId = event.thread_id;
        else if (event.type === "item.completed" && event.item?.type === "agent_message") content = event.item.text;
        else if (event.type === "turn.failed" || event.type === "error") error = event.error?.message ?? event.message ?? line;
      } catch { /* not an event */ }
    });
    child.stderr!.on("data", (data: Buffer) => { stderr = `${stderr}${data.toString("utf8")}`.slice(-4000); });
    const finish = (code: number | null) => {
      children.delete(id);
      const failed = code !== 0 || (error && !content);
      const text = failed ? (error || stderr.trim() || `codex exited with ${code}`) : content;
      resolve({ content: [{ type: "text", text }], structuredContent: { threadId, content: text }, ...(failed ? { isError: true } : {}) });
    };
    child.once("error", (spawnError) => { stderr = spawnError.message; finish(-1); });
    child.once("close", finish);
  });
}

/**
 * `codex mcp-server` (removed from codex in 0.154): the same stdio MCP server, running each call as a `codex exec`
 * session of the installed codex. Sessions are `exec`-sourced (hidden from Desktop's list) and persist their
 * rollouts, so Claude threads stream them and `codex-reply` resumes them.
 */
export async function runMcpServer(config: Config, version: string, input: Readable = process.stdin, output: Writable = process.stdout): Promise<number> {
  const children = new Map<unknown, ChildProcess>();
  const send = (message: object) => output.write(`${JSON.stringify({ jsonrpc: "2.0", ...message })}\n`);
  const lines = createInterface({ input });
  lines.on("line", (line) => {
    let message: Args;
    try { message = JSON.parse(line) as Args; } catch { return; }
    const { id, method, params } = message;
    if (method === "notifications/cancelled") children.get(params?.requestId)?.kill("SIGTERM");
    if (id === undefined || method === undefined) return;
    if (method === "initialize") {
      send({ id, result: { protocolVersion: params?.protocolVersion ?? "2025-06-18", capabilities: { tools: { listChanged: false } }, serverInfo: { name: "codex-mcp-server", title: "Codex", version } } });
    } else if (method === "tools/list") {
      send({ id, result: { tools: TOOLS } });
    } else if (method === "tools/call" && TOOLS.some((tool) => tool.name === params?.name)) {
      void runCall(config, params.name, params.arguments ?? {}, children, id).then((result) => send({ id, result }));
    } else if (method === "ping") {
      send({ id, result: {} });
    } else {
      send({ id, error: { code: -32601, message: `Method not found: ${method}` } });
    }
  });
  await new Promise((resolve) => lines.once("close", resolve));
  for (const child of children.values()) child.kill("SIGTERM");
  return 0;
}
